### ISSUE TITLE
ESP32 with W5500 and platform 3 compille error

### ISSUE THREAD

**Issue by proasnet** [ciniml/WireGuard-ESP32-Arduino#45]
ESP32 with connected W5500 ethernet adapter, esp platform 3 compille error
```
C:\Users\j.jirutka\Documents\Arduino\libraries\WireGuard-ESP32\src\wireguardif.c:51:10: fatal error: tcpip_adapter.h: No such file or directory
   51 | #include "tcpip_adapter.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by alfersi** [comment]
I had the exact same issue, the only way to get it to compile is switching to a platform version <3.0.0, the reason being that version 3.0.0 and higher doesn't include the TCP/IP Adapter library anymore, having been deprecated in favour of ESP NETIF. I understand that for this library to work with ESP NETIF it  would require a complete review a rewrite following the migration guide, however I don't know if there's a fork that already includes these changes or if anyone is willing to do it. My suggestion would be to use platformIO where you can specifify the platform version, and hence the ESP-IDF version, in this case Arduino ESP32 version 2.0.17 uses ESP-IDF v4.4.7, in platformIO you can specify:

`[env:my-esp32]
platform = espressif32 @ 5.4.0`

which uses ESP-IDF v4.4.3 and should compile nicely, I've tested it and it does work, whilst I was unable to compile in Arduino IDE unless I downgraded ESP32 platform to 2.0.17. Then I went on and tested with platform 6.7.0, which is the latest, and it does indeed work. It's known that Arduino IDE and Arduino framework inside platwormIO diverge substantially, so this must be one of those cases. At any rate I've always found PIO better for developing.

**Comment by nmingotti** [comment]
a pity, if anybody is willing to fork/adapt the software to make it compile and work again in the Arduino IDE (Linux) for Heltec Wifi Kit 32(V3)  (which i use most recently) will be ready to give and hand financially say 100€.

**Comment by martinusGH** [comment]
I had the same issue when migrating from Arduino 2.x to 3.0.7. I managed to patch the source code myself and it worked again until I upgraded to Arduino 3.1.0. Broken again, again several hours of debugging, but managed to fix it again. Needs a lot of Mutexes wrapped around many calls to net_if.
Unfortunately this library seems to be abandoned as it has not seen any updates for three years.

**Comment by alpintrekker** [comment]
@martinusGH would you mind to share your results, maybe in a forked repository?

**Comment by martinusGH** [comment]
I've trashed my github development setup a few years ago, and not really planning to restart that. I can try to add the two patched files in here, hope you are able to use those into a working solution. My skills seemed sufficient to make this library work again, but really someone with deep knowledge on ESP32-IDF based networking should try to take over the maintenance of this library.
[WireGuard.zip](https://github.com/user-attachments/files/18358715/WireGuard.zip)

**Comment by alpintrekker** [comment]
Thank you very much @martinusGH  for sharing your work! 

However, the supplied archive seems to miss an updated version of WireGuard-ESP32.h, if am I not getting wrong the following error messages:

`/home/bandi/Arduino/libraries/WireGuard-ESP32/src/WireGuard.cpp:44:6: error: no declaration matches 'bool WireGuard::begin(const IPAddress&, const IPAddress&, const IPAddress&, const char*, const char*, const char*, uint16_t)'
   44 | bool WireGuard::begin(const IPAddress& localIP, const IPAddress& Subnet, const IPAddress& Gateway, const char* privateKey, const char* remotePeerAddress, const char* remotePeerPublicKey, uint16_t remotePeerPort) {
      |      ^~~~~~~~~
In file included from /home/bandi/Arduino/libraries/WireGuard-ESP32/src/WireGuard.cpp:6:
/home/bandi/Arduino/libraries/WireGuard-ESP32/src/WireGuard-ESP32.h:13:10: note: candidate is: 'bool WireGuard::begin(const IPAddress&, const char*, const char*, const char*, uint16_t)'
   13 |     bool begin(const IPAddress& localIP, const char* privateKey, const char* remotePeerAddress, const char* remotePeerPublicKey, uint16_t remotePeerPort);`

I tried to compile the WireGuard-ESP32 v0.1.5 with your patched files on esp32 3.0.7, 3.1.0 and 3.1.1 with similar results.
I'd appreciate any advice, bests

**Comment by martinusGH** [comment]
I cannot remember changing that file, but let me just upload the entire library that I have now
[WireGuard-ESP32.zip](https://github.com/user-attachments/files/18385287/WireGuard-ESP32.zip)
I double checked with the provided sample from the library "disconnect", compiles without issues on my end.

**Comment by pierrejay** [comment]
If useful to anyone, I saw that ESPHome had done an implementation that works on the 3.0+ core, so I made a port that looks to be working fine with better performance than the patched library (typically getting ~30ms better round-trip time on incoming pings & HTTP requests).

You can find it [here](https://github.com/pierrejay/esp32-tailbridge/tree/main/esp32-arduino-example) within another project I have done using the lib.

N.B. : some build flags must be added to `platformio.ini` (same as in the ESPHome implementation):
```ini
build_flags = 
  -DCONFIG_WIREGUARD_MAX_SRC_IPS=4
  -DCONFIG_WIREGUARD_MAX_PEERS=1
```

**Comment by freitas666** [comment]
Hello guys,

This Wireguard-ESP32.zip works in Esp32-s3? I am trying compile and have problems with tcpip_adapter.h..

Forgive me, i am not a pro on this...

**Comment by pierrejay** [comment]
Yes, tested the archive with both c3 and s3 and it was working fine. `tcpip_adapter.h` is no longer included in this version so you might be using the wrong version of the lib.

**Comment by freitas666** [comment]
> Yes, tested the archive with both c3 and s3 and it was working fine. `tcpip_adapter.h` is no longer included in this version so you might be using the wrong version of the lib.

My friend could you share the part of configs in your .Ino?

I guess something is wrong on mine.. because my esp32s3 all time is disconnecting and reconnect as restarting usb :(

**Comment by pierrejay** [comment]
Personally I am using PlatformIO (`pioarduino` platform) not Arduino IDE. 

I believe you should first uninstall the WireGuard-ESP32 library in Arduino IDE's Library Manager and after only, add the .zip in `Sketch > Include Library`. 

I just tried it with martinusGH's version and got some compilation errors. One function definition was missing in `wireguard.h`. Try this archive, it works for me with `XIAO_ESP32S3` with core 3.2.0. I can see the ESP32 connecting to my server and it responds to pings.

[WireGuard-ESP32-bis.zip](https://github.com/user-attachments/files/19623880/WireGuard-ESP32-bis.zip)

**Comment by freitas666** [comment]
> Personally I am using PlatformIO (`pioarduino` platform) not Arduino IDE.
> 
> I believe you should first uninstall the WireGuard-ESP32 library in Arduino IDE's Library Manager and after only, add the .zip in `Sketch > Include Library`.
> 
> I just tried it with martinusGH's version and got some compilation errors. One function definition was missing in `wireguard.h`. Try this archive, it works for me with `XIAO_ESP32S3` with core 3.2.0. I can see the ESP32 connecting to my server and it responds to pings.
> 
> [WireGuard-ESP32-bis.zip](https://github.com/user-attachments/files/19623880/WireGuard-ESP32-bis.zip)

Thank you, i will try it and soon back with results :D

**Comment by freitas666** [comment]
Hello @pierrejay i followed this steps that you send me and my code works perfectly! no more errors, compile good and works connecting on my wireguard server!

**Thank you so much!**
